spring.application.name=tesis-backend

## Conexion a PostgreSQL ##
spring.datasource.url=jdbc:postgresql://localhost:5433/tesis-db
spring.datasource.username=postgres
spring.datasource.password=mateodf208
spring.jpa.hibernate.ddl-auto=update