spring.application.name=tesis-backend

## Conexion a PostgreSQL ##
spring.datasource.url=jdbc:postgresql://localhost:5433/tesis-db
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

## Hibernate/JPA ##
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## MIS COSAS ##
## API Read Acces Token de TMDB
tmdb.api.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzZTYxM2E0OTJmM2NmM2YyNDQ4YjI1ZDIwNDA0NjU5YiIsIm5iZiI6MTc0Njc0NzA5Ny41NjQsInN1YiI6IjY4MWQzZWQ5ZGM5MzcyODViYzg4YzQ5ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.oC1aoBd1dydoOnfiReVSlMz-WCKd_RCwGxlp079sY4I